GET http://localhost:3000/events
###
POST http://localhost:3000/events
Content-Type: application/json

{
"name": "My Event",
"description": "A great event",
"date": "2017-01-01T00:00:00.00",
"price": 100
}